### ISSUE TITLE
Can't load game

### ISSUE THREAD

**Issue by ffaf1** [JustThomi/KingOink#1]
```
f@mkiii:~/download/KingOink$ python3 main.py
pygame 2.1.2 (SDL 2.26.5, Python 3.11.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/f/download/KingOink/main.py", line 90, in <module>
    main()
  File "/home/f/download/KingOink/main.py", line 67, in main
    pygame.mixer.music.load("assets\sounds\music.mp3")
pygame.error: No file 'assets\sounds\music.mp3' found in working directory '/home/f/download/KingOink'.
```

Quite weird since the file is there!

```
f@mkiii:~/download/KingOink$ ls assets/sounds/music.mp3
assets/sounds/music.mp3
```
 
System: Debian GNU/Linux 12.1

**Comment by JustThomi** [comment]
I think it was bc I messed up the path and didn't start it with ./
I just pushed a hotfix and I think it should work now.

**Comment by ffaf1** [comment]
works, thanks!
